---
- hosts: grafana 
  become: yes
  remote_user: root
  vars:
    package_names:
      - grafana

  tasks:
    - name: Get stats of installed Grafana
      ansible.builtin.stat:
        path: /etc/grafana/grafana.ini
      register: sys

    - name: gafana is installed
      debug:
        msg: gafana is installed
      when: sys.stat.exists

    - name: gafana is NOT installed
      debug:
        msg: gafana is installed
      when: not sys.stat.exists

    - block:
        - import_role:
            name: grafana
      when: not sys.stat.exists
