---
- hosts: prometheus 
  become: yes
  remote_user: root
  vars:
    package_names:
      - prometheus

  tasks:
    - name: Get stats of installed Prometheus
      ansible.builtin.stat:
        path: /etc/prometheus/prometheus.yml
      register: exists

    - block:
        - import_role:
            name: prometheus
      when: exists.stat.exists is not defined
