---
- hosts: grafana 
  become: yes
  remote_user: root
  vars:
    package_names:
      - grafana

  tasks:
    - name: "Check if listed package is installed or not on Debian Linux family"
      command: dpkg-query -l "{{ item }}"
      loop: "{{ package_names }}"
      register: debian_package_check
      when: ansible_facts['os_family'] == "Debian"

    - block:
        - import_role:
            name: grafana
      when: debian_package_check is failed
