---
- hosts: prometheus 
  become: yes
  remote_user: root
  vars:
    package_names:
      - prometheus

  tasks:
    - name: Get stats of installed node_exporter
      ansible.builtin.stat:
        path: /etc/systemd/system/node_exporter.service
      register: sys
    
    - name: node_exporter is installed
      debug:
        msg: node_exporter is installed
      when: sys.stat.exists

    - name: node_exporter is NOT installed
      debug:
        msg: node_exporter is NOT installed
      when: not sys.stat.exists

    - block:
        - import_role:
            name: node_exporter
      when: not sys.stat.exists
