---
- hosts: grafana 
  become: yes
  remote_user: root
  vars:
    package_names:
      - grafana

  tasks:
    - name: Get stats of installed Grafana
      ansible.builtin.stat:
        path: /etc/gafana/grafana.ini
      register: sys

    - block:
        - import_role:
            name: grafana
      when: not sys.stat.exists
