---

- name: GRAFANA | grafana group
  group:
    name: "{{ grafana_group }}"

- name: GRAFANA | grafana user
  user:
    name: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    shell: /bin/bash


- name: GRAFANA | create paths
  file:
    dest: "{{ item }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    state: directory
  with_items:
    - "{{ grafana_skeleton_paths }}"

# ------------------------

- name: Install a .deb package from the internet
  ansible.builtin.apt:
    deb: https://dl.grafana.com/oss/release/grafana_9.5.1_amd64.deb

# -------------------

- name: GRAFANA | Copy Daemon script
  template:
    src: "{{ grafana_service_template_path }}"
    dest: /usr/lib/systemd/system/grafana-server.service
    mode: 0644
  notify: restart grafana
  when: grafana_service_template_path is defined
